# DESCRIPTION: 	
# Builds and tests projects in the repository

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/FhirLoader.BulkImport
pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/FhirLoader.BulkImport

parameters:
  - name: targetBuildFramework
    type: string
    default: 'net6.0'

variables:
  - name: VmImage
    value: 'ubuntu-latest'
  - name: WindowsVmImage
    value: 'windows-latest'

stages:
  - stage: Build

    jobs:
    - job: CodeChecks
      pool:
        vmImage: $(WindowsVmImage)
      steps:
      - template: ./jobs/checkCode.yml
        parameters:
          DotNetVersion: '6.0.x'

    - job: BuildTestPublish
      pool:
        vmImage: $(WindowsVmImage)
      steps:
      - template: ./jobs/update-semver.yml
        parameters:
          DotNetVersion: '6.0.x'
      - template: ./jobs/build.yml
        parameters:
          DotNetVersion: '6.0.x'
          SourceProjectsString: '**/FhirLoader.BulkImport.csproj'
          UnitTest: false
          AssemblyVersion: $(assemblySemVer)
          FileVersion: $(assemblySemFileVer)
          InformationalVersion: $(informationalVersion)
          Version: $(majorMinorPatch)
      - template: ./jobs/publish.yml
        parameters:
          DotNetVersion: '6.0.x'
          SourceProjectsString: '**/FhirLoader.BulkImport.csproj'
          PackageArtifactName: 'FhirLoader.BulkImport'
          Version: $(majorMinorPatch)
          VersionSuffix: $(build.buildNumber)

#  - stage: 
#    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
#    jobs:
#      - job: B1