# DESCRIPTION: 	
# Builds and tests projects in the repository

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/FhirLoader.BulkImport
pr:
  branches:
    include:
      - main
  paths:
    include:
      - src/FhirLoader.BulkImport

parameters:
  - name: targetBuildFramework
    type: string
    default: 'net6.0'

variables:
  - name: VmImage
    value: 'ubuntu-latest'
  - name: WindowsVmImage
    value: 'windows-latest'
  - name: DotNetVersion
    value: '7.0.x'
  - name: ProjectName
    value: 'FhirLoader.slh'
  - name: SourceProjectsString
    value: '**/FhirLoader.BulkImport.csproj'
  - name: TestProjectsString
    value: ''
  - name: PackageArtifactName
    value: 'FhirLoader.BulkImport'

stages:
  - stage: Build

    jobs:
    - job: CodeChecks
      pool:
        vmImage: ${{ variables.WindowsVmImage }}
      steps:
      - template: ./jobs/checkCode.yml

    - job: BuildTestPublish
      pool:
        vmImage: ${{ variables.WindowsVmImage }}
      steps:
      - template: ./jobs/update-semver.yml
        parameters:
          DotNetVersion: '7.0.x'
      - template: ./jobs/build.yml
        parameters:
          UnitTest: false
          AssemblyVersion: $(assemblySemVer)
          FileVersion: $(assemblySemFileVer)
          InformationalVersion: $(informationalVersion)
          Version: $(majorMinorPatch)
      - template: ./jobs/publish.yml
        parameters:
          Version: $(majorMinorPatch)
          VersionSuffix: $(build.buildNumber)

#  - stage: 
#    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
#    jobs:
#      - job: B1