parameters:
  unitTest: true
  componentGovernance: false
  targetBuildFramework: ''
  srcProjectsString: ''
  testProjectsString: ''

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    useGlobalJson: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-incremental -p:ContinuousIntegrationBuild=true -warnaserror -f ${{parameters.targetBuildFramework}}'
    projects: ${{ parameters.srcProjectsString }}}
  displayName: 'Build toolkit projects'

- ${{ if eq(parameters.componentGovernance, 'true') }}:
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
      failOnAlert: true

- ${{ if eq(parameters.unitTest, 'true') }}:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      arguments: '--no-build --configuration $(buildConfiguration) -f ${{parameters.targetBuildFramework}}'
      publishTestResults: true
      projects: ${{ parameters.testProjectsString }}}
    displayName: 'Run all tests'