parameters:
  - name: DotNetVersion
  - name: SourceProjectsString
  - name: TestProjectsString
  - name: RunUnitTest
  - name: RunComponentGovernance
  - name: AssemblyVersion
  - name: FileVersion
  - name: InformationalVersion
  - name: Version

steps:
  - task: UseDotNet@2
    displayName: "Use .NET SDK"
    inputs:
      version: ${{ parameters.DotNetVersion }}

  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      arguments: '--configuration Release --no-incremental -p:ContinuousIntegrationBuild=true -p:AssemblyVersion="${{ parameters.AssemblyVersion }}" -p:FileVersion="${{ parameters.FileVersion }}" -p:InformationalVersion="${{ parameters.InformationalVersion }}" -p:Version="${{ parameters.Version }}" -warnaserror'
      projects: ${{ parameters.SourceProjectsString }}
    displayName: "Build toolkit projects"

  - ${{ if eq(parameters.RunComponentGovernance, 'true') }}:
      - task: RunComponentGovernanceComponentDetection@0
        inputs:
          scanType: "Register"
          verbosity: "Verbose"
          alertWarningLevel: "High"
          failOnAlert: true

  - ${{ if eq(parameters.RunUnitTest, 'true') }}:
      - task: DotNetCoreCLI@2
        inputs:
          command: "test"
          arguments: "--no-build --configuration Release"
          publishTestResults: true
          projects: ${{ parameters.TestProjectsString }}
        displayName: "Run all tests"
