parameters:
  - name: UnitTest
    default: true
  - name: componentGovernance
    default: false
  - name: AssemblyVersion
  - name: FileVersion
  - name: InformationalVersion
  - name: Version

steps:

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      version: ${{ variables.DotNetVersion }}

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration Release --no-incremental -p:ContinuousIntegrationBuild=true -p:AssemblyVersion="${{ parameters.AssemblyVersion }}" -p:FileVersion="${{ parameters.FileVersion }}" -p:InformationalVersion="${{ parameters.InformationalVersion }}" -p:Version="${{ parameters.Version }}" -warnaserror'
      projects: 
    displayName: 'Build toolkit projects'

  - ${{ if eq(parameters.componentGovernance, 'true') }}:
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'
        failOnAlert: true

  - ${{ if eq(parameters.unitTest, 'true') }}:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '--no-build --configuration Release'
        publishTestResults: true
        projects: ${{ variables.TestProjectsString }}
      displayName: 'Run all tests'